# listen addr of http api server
addr = ":5000"

#sqlite3 database name
db_name = "./data/STT_DB.db"

#jwt secret key
jwt_secret = "1TXwNU2x2j8x7bay5pmKeoBtRKir/FM1V8GbHc3lqOg="

#session exipery timeout in seconds
web_session_timeout = 86400

